export const locale = 'ru-RU';

export const text = {
  app: {
    documentTitle: 'Чат с ИИ-агентом',
    productName: 'ИИ-агент',
  },
  sidebar: {
    title: 'Чаты',
    newChat: 'Новый',
    chatLimit: (count: number, max: number) => `${count}/${max} чатов`,
    chatLimitReached: 'Достигнут лимит чатов.',
    loadingChats: 'Загрузка чатов...',
    emptyChats: 'Чатов пока нет. Создайте чат, чтобы начать.',
    rename: 'Переименовать',
    delete: 'Удалить',
  },
  chat: {
    currentChat: 'Текущий чат',
    noChatSelected: 'Чат не выбран',
    selectOrCreateChat: 'Выберите или создайте чат.',
    emptyMessages: 'Напишите агенту первый вопрос.',
    jumpToLatest: 'К последнему сообщению',
  },
  connection: {
    connected: 'Подключено',
    connecting: 'Подключение',
    idle: 'Ожидание',
  },
  composer: {
    placeholder: 'Напишите агенту...',
    disabledPlaceholder: 'Сначала создайте чат',
    send: 'Отправить',
    sending: 'Отправка...',
    hint: 'Enter отправляет сообщение. Shift + Enter добавляет новую строку.',
  },
  message: {
    user: 'Вы',
    assistant: 'Ассистент',
    thinking: 'Ход рассуждений',
    generating: 'Генерация ответа...',
    status: {
      pending: 'ожидает отправки',
      sent: 'отправлено',
      streaming: 'генерируется',
      failed: 'ошибка',
      complete: 'готово',
    },
  },
  modal: {
    renameSection: 'Настройки чата',
    renameTitle: 'Переименовать чат',
    titleField: 'Название',
    dangerSection: 'Опасное действие',
    deleteTitle: 'Удалить чат',
    deleteCopy: (title: string) => `Удалить "${title}"? Чат и все его сообщения будут удалены.`,
    cancel: 'Отмена',
    save: 'Сохранить',
    saving: 'Сохранение...',
    delete: 'Удалить',
    deleting: 'Удаление...',
  },
  actions: {
    retry: 'Повторить',
  },
  errors: {
    requestFailed: (status: number) => `Запрос завершился с ошибкой ${status}.`,
    loadChats: 'Не удалось загрузить чаты.',
    loadMessages: 'Не удалось загрузить историю чата.',
    websocketFailed: 'Не удалось подключиться к чату.',
    modelResponseFailed: 'Не удалось получить ответ от модели.',
    chatLimitReached: 'Достигнут лимит чатов. Удалите один чат перед созданием нового.',
    createChat: 'Не удалось создать чат.',
    titleRequired: 'Введите название чата.',
    renameChat: 'Не удалось переименовать чат.',
    deleteChat: 'Не удалось удалить чат.',
    messageRequired: 'Введите сообщение.',
    messageTooLong: 'Сообщение длиннее 4000 символов.',
  },
} as const;
